### PR TITLE
Added page for Supporters

### LINKED ISSUE #4: Create Features Page for CARE
We need to create a comprehensive Features Page for the CARE EMR system on the ohc.network website. This page should outline and detail all the features offered by CARE to ensure visitors have a clear understanding of its capabilities. Below is the list of features that need to be included on the page, organized by category:

**Features to Include:**

**Facility Management:**

- **Assets**: Overview of asset management capabilities, including tracking and maintenance.
- **Locations**: Information on location-based management and operations within CARE.
- **Beds**: Bed management, availability, and allocation features.
- **Resources**: Resource tracking and management functionalities.
- **Resource Requests**: Emergency resource requests (e.g., oxygen supplies) and their handling.
- **Capacity Monitoring**: Real-time capacity monitoring and reporting features.
- **Notice Board**: Centralized notice board for announcements and updates.
- **Notifications**: Notification system for alerts and updates to users.

**Patient Management:**

- **Patients**: Comprehensive patient management features.
- **Consultations**: Managing and documenting patient consultations.
- **Rounds**: Features to support medical rounds and their documentation.
- **Investigations**: Management of patient investigations and tests.
- **ABG**: Arterial Blood Gas (ABG) test management.
- **Files**: Document management, including patient records and files.
- **Discharge Summary**: Generation and management of discharge summaries.
- **Scribe**: AI-powered autofilling of EMR records to reduce manual data entry.
- **Patient Shifting**: Management of patient transfers between departments or facilities.
- **Sample Tests**: Handling and documentation of various sample tests.
- **ICD11 Diagnosis**: Support for ICD11 diagnosis coding and documentation.

**TeleICU Features:**

- **Live Camera Feed**: Real-time video feeds from ICU units.
- **Live 5 Para Monitor/Ventilator Readings**: Live monitoring of vital signs and ventilator readings.
- **Doctor Connect via WhatsApp Video Calls**: Direct connection with doctors through WhatsApp video calls.
- **Doctor Notes/Discussions for Patients**: Features for doctors to leave notes and discuss patient cases.

**Integrations:**

- **HCX Integration**: Integration with Health Claims Exchange (HCX).
- **ABDM Integration**: Integration with the Ayushman Bharat Digital Mission (ABDM).
- **HL7 FHIR-based Medical Device Integrations**: Integration with medical devices using HL7 FHIR standards.
- **ONVIF-based Camera Integration**: Integration with cameras using ONVIF standards.

### PR DESCRIPTION
**Pull request by shivankacker**
fixes #4

### CODE REVIEW

**Comment by tomahawk-pilot** [comment]
#### 📝 Changed routes:


| [**/care**](https://landing-fd7layslg-ohcnetwork.vercel.app/care) | [**/**](https://landing-fd7layslg-ohcnetwork.vercel.app/) |
|:-:|:-:|
|<a href="https://landing-fd7layslg-ohcnetwork.vercel.app/care">Screenshot of /care</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/loTmSGo8uu8LCHOQgx9M5P7C7p7jlw92wYXrmEC0ZHAP4kDkBMxAQb55nC2M-n3p2bQjlGZLnRHzAWFXP8zSbw.png">(view full size)</a> |<a href="https://landing-fd7layslg-ohcnetwork.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/J9erMrlzu1BaNsgCoY3grxtU0Pb1ah87bY67FzLJ7kVuKUAJG-5L1D9p9BNyM-UFly0sJ271BVixR4yef1lMwg.png">(view full size)</a> |





1 deleted route:
- **/api/hello**

Commit 137b646543d46f12c4fe07b364a8a25c93008c96 (https://landing-fd7layslg-ohcnetwork.vercel.app).

**Comment by gigincg** [comment]
@shivankacker Can you stash Products for now, fix the Header and add a Supporters Page. Let's expedite and ship these by tomorrow, and work on Products pages separately

**Comment by nihal467** [comment]
@shivankacker 
image

- [ ] When you hover over the supporters' icons, the cursor indicates that they are clickable, but clicking on them does not redirect you to any page.

image

- [ ] the footer is missing for this supporters page, was that intentional kept like that ?

image

- [ ] Icons such as OpenAI, GitHub, CircleCI, Sentry, and Vercel don't have a hover effect. If the icons are fully black, apply a grey shade like we have for the Cloudflare icon. Then, on hover, display the fully black version of the icon.
- [ ] For example, some icons like Slack have the text in full black while the corresponding icon has a greyed-out effect. To keep it consistent across the page, apply the same grey shade to both the icon and the text. On hover, display them in full color. 



cc; @gigincg

**Comment by shivankacker** [comment]
@nihal467 

1 : I put everything Bodhi and Syam asked, is there a list with all the requested supporters? 
2, 4, 5 : I turned the grayscale effect off all together, and removed the pointer cursor
3: Added footer
6: Added page title

**Pull request merged**
